apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: foundit-db-ingress
  labels:
    app: foundit-db
spec:
  podSelector:
    matchLabels:
      app: foundit-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: foundit-backend
        - podSelector:
            matchLabels:
              app: foundit-db-backup
        - podSelector:
            matchLabels:
              app: foundit-data-retention
      ports:
        - protocol: TCP
          port: 5432
