apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundit-db-pvc
  labels:
    app: foundit-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundit-db
  labels:
    app: foundit-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundit-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: foundit-db
    spec:
      containers:
        - name: db
          image: ghcr.io/znatom/find-my-bot-db:latest
          env:
            - name: POSTGRES_USER
              value: "appuser"
            - name: POSTGRES_PASSWORD
              value: "password" # IN PRODUCTION: Use K8s Secrets instead
            - name: POSTGRES_DB
              value: "lostfound"
            - name: HF_LOCAL_ONLY
              value: "1"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - appuser
                - -d
                - lostfound
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: foundit-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: foundit-db
  labels:
    app: foundit-db
spec:
  ports:
    - port: 5432
      targetPort: postgres
  selector:
    app: foundit-db
