apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db.yaml
- frontend.yaml
- backend.yaml
- ingress.yaml

# These image tags will be replaced dynamically by the CI/CD pipeline
images:
- name: ghcr.io/znatom/find-my-bot-backend
  newName: ghcr.io/znatom/find-my-bot-backend
  newTag: sha-30d0ea10556610901bfb6a7d5d31c482058b464e
- name: ghcr.io/znatom/find-my-bot-db
  newName: ghcr.io/znatom/find-my-bot-db
  newTag: sha-30d0ea10556610901bfb6a7d5d31c482058b464e
- name: ghcr.io/znatom/find-my-bot-frontend
  newName: ghcr.io/znatom/find-my-bot-frontend
  newTag: sha-30d0ea10556610901bfb6a7d5d31c482058b464e
