apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db.yaml
- frontend.yaml
- backend.yaml
- ingress.yaml

# These image tags will be replaced dynamically by the CI/CD pipeline
images:
- name: ghcr.io/znatom/find-my-bot-backend
  newName: ghcr.io/znatom/find-my-bot-backend
  newTag: sha-5e434007fa6d30a16feab9f9b5078e4e3d680115
- name: ghcr.io/znatom/find-my-bot-db
  newName: ghcr.io/znatom/find-my-bot-db
  newTag: sha-5e434007fa6d30a16feab9f9b5078e4e3d680115
- name: ghcr.io/znatom/find-my-bot-frontend
  newName: ghcr.io/znatom/find-my-bot-frontend
  newTag: sha-5e434007fa6d30a16feab9f9b5078e4e3d680115
