apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- db.yaml
- frontend.yaml
- backend.yaml
- ingress.yaml

# These image tags will be replaced dynamically by the CI/CD pipeline
images:
- name: ghcr.io/znatom/find-my-bot-backend
  newName: ghcr.io/znatom/find-my-bot-backend
  newTag: sha-dc24472398e24af20bcc740aad565348c9268545
- name: ghcr.io/znatom/find-my-bot-db
  newName: ghcr.io/znatom/find-my-bot-db
  newTag: sha-dc24472398e24af20bcc740aad565348c9268545
- name: ghcr.io/znatom/find-my-bot-frontend
  newName: ghcr.io/znatom/find-my-bot-frontend
  newTag: sha-dc24472398e24af20bcc740aad565348c9268545
